"""including default fields for payments

Revision ID: 1ab0c65fec38
Revises: 2cdb61e2b2b8
Create Date: 2024-05-12 18:15:27.600651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab0c65fec38'
down_revision: Union[str, None] = '2cdb61e2b2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
