"""adding admin model

Revision ID: 2924e370b8db
Revises: 404a6488d086
Create Date: 2024-05-12 11:36:56.945084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2924e370b8db'
down_revision: Union[str, None] = '404a6488d086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('admin', 'name')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admin', 'role')
    op.drop_column('admin', 'lastname')
    op.drop_column('admin', 'firstname')
    # ### end Alembic commands ###
