"""Creating signup token model

Revision ID: 2cdb61e2b2b8
Revises: ad90aef4d781
Create Date: 2024-05-12 13:05:54.296078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdb61e2b2b8'
down_revision: Union[str, None] = 'ad90aef4d781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
