"""Added tables for procurement item

Revision ID: 39f4068ddcf5
Revises: 59a333523c91
Create Date: 2024-05-19 20:45:25.758210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f4068ddcf5'
down_revision: Union[str, None] = '59a333523c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_procurement_item_id', table_name='procurement_item')
    op.drop_table('procurement_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_resold_to_babies', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sold_to_babies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sold_to_babies'], ['baby.id'], name='procurement_item_sold_to_babies_fkey'),
    sa.PrimaryKeyConstraint('id', name='procurement_item_pkey')
    )
    op.create_index('ix_procurement_item_id', 'procurement_item', ['id'], unique=False)
    # ### end Alembic commands ###
