"""adding payment type

Revision ID: 404a6488d086
Revises: d65d85763b48
Create Date: 2024-05-12 01:05:08.417790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404a6488d086'
down_revision: Union[str, None] = 'd65d85763b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby', 'payment_type')
    # ### end Alembic commands ###
