"""adding status to present babies

Revision ID: 59a333523c91
Revises: 47d53be61c40
Create Date: 2024-05-19 12:34:18.413720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a333523c91'
down_revision: Union[str, None] = '47d53be61c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('present_baby', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('present_baby', 'status')
    # ### end Alembic commands ###
