"""change time in  tables for procurement item

Revision ID: 7efb19d747f3
Revises: 39f4068ddcf5
Create Date: 2024-05-19 21:09:38.346296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efb19d747f3'
down_revision: Union[str, None] = '39f4068ddcf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
