"""Updating both tables

Revision ID: 9d044c0b0614
Revises: 8787d6d0ae0d
Create Date: 2024-05-11 23:38:01.156604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d044c0b0614'
down_revision: Union[str, None] = '8787d6d0ae0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby', sa.Column('location', sa.String(), nullable=True))
    op.add_column('baby', sa.Column('name_of_brought_person', sa.String(), nullable=True))
    op.add_column('baby', sa.Column('time_of_arrival', sa.DateTime(), nullable=True))
    op.add_column('baby', sa.Column('name_of_parent', sa.String(), nullable=True))
    op.add_column('baby', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('baby', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('baby', sa.Column('baby_access', sa.String(), nullable=True))
    op.add_column('baby', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('baby', sa.Column('is_monthly', sa.Boolean(), nullable=True))
    op.add_column('payment', sa.Column('number_of_babies', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('payment', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.drop_column('payment', 'is_monthly')
    op.drop_column('payment', 'duration')
    op.add_column('sitter', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('sitter', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitter', 'status')
    op.drop_column('sitter', 'contact')
    op.add_column('payment', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('is_monthly', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('payment', 'is_paid')
    op.drop_column('payment', 'payment_date')
    op.drop_column('payment', 'total_amount')
    op.drop_column('payment', 'number_of_babies')
    op.drop_column('baby', 'is_monthly')
    op.drop_column('baby', 'date')
    op.drop_column('baby', 'baby_access')
    op.drop_column('baby', 'duration')
    op.drop_column('baby', 'fee')
    op.drop_column('baby', 'name_of_parent')
    op.drop_column('baby', 'time_of_arrival')
    op.drop_column('baby', 'name_of_brought_person')
    op.drop_column('baby', 'location')
    # ### end Alembic commands ###
