"""updating the admin model so that it is in position to make emails unique and role default

Revision ID: ad90aef4d781
Revises: 2924e370b8db
Create Date: 2024-05-12 12:17:38.647753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90aef4d781'
down_revision: Union[str, None] = '2924e370b8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
